### ISSUE TITLE
Suggest using short description to summarize what's in the mod

### ISSUE THREAD

**Issue by HebaruSan** [JamesErvin-5/AtomicTech-Inc.-Junkyards#11]
A user who doesn't already know what this mod is would still have no idea what it is after reading [the short description on SpaceDock](https://spacedock.info/mod/2891/AtomicTech%20Inc.%20Junkyards):

![image](https://user-images.githubusercontent.com/1559108/144713128-f2ab89d6-d7b5-419b-b7ae-10c90803c551.png)

The previous short descriptions don't help much either:

- > New 5m, 3.75m, 2.5m, and 1.875m Greenhouses and a new Pod and two Science Bays Have Arrived!
  > Now with 5m, 3.75m, 2.5m, and 1.875m Greenhouses!
  > New Greenhouses!
  > 80-90% Done! Everything should be working so far!

  These are more like changelog entries; they describe just the latest changes and assume that the reader knows what was already in the mod previously.

- > New 5m, 3.75m, 2.5m, and 1.875m Greenhouses and a new Pod + Science Bay Coming Soon!
  > Greenhouse bug fixes coming soon!
  > 5m, 3.75m, 2.5m, and 1.875m Greenhouses Coming Soon!

  These are more like roadmap entries; they tell the reader about future plans, but not what they'll get if they choose to download and install the current version.

Imagine a user looking at the SpaceDock page (or CKAN listing) for the mod for the first time and trying to decide whether to download it. To make this decision, they need to know: _What is contained in the mod's ZIP file, and what will change in my game if I install this mod?_

To give you an example, this from the forum thread is the closest thing I can find to a true short description in the materials currently available:

> quality of life improvements in a few parts and improved performance on a few others

**Comment by JamesErvin-5** [comment]
Already working on it!

**Comment by HebaruSan** [comment]
Cool, good luck in your efforts!

Taking a look at the current description, it seems to satisfy this suggestion well enough to close it. Cheers!
