### ISSUE TITLE
EVA Suits Not Appearing!

### ISSUE THREAD

**Issue by JamesErvin-5** [JamesErvin-5/AtomicTech-Inc.-Junkyards#12]
Help!

**Comment by staticalliam7** [comment]
May be helpful: [https://forum.kerbalspaceprogram.com/index.php?/topic/195242-make-your-own-custom-colored-suits-with-kerbal-space-program-110-shared-horizons%E2%80%9D/](https://forum.kerbalspaceprogram.com/index.php?/topic/195242-make-your-own-custom-colored-suits-with-kerbal-space-program-110-shared-horizons%E2%80%9D/)

**Comment by JamesErvin-5** [comment]
I looked at that and did the code from there. I must've missed something then.
