### ISSUE TITLE
EVA suits?

### ISSUE THREAD

**Issue by staticalliam7** [JamesErvin-5/AtomicTech-Inc.-Junkyards#6]
Something like an attachable EMU to make the stock suits look cooler (I know historicsuits does this but it lacks a large jetpack)
![maxresdefault](https://user-images.githubusercontent.com/63507206/144110442-f4d25987-e230-46dd-af3d-abb3c74d5192.jpg)
l

**Comment by JamesErvin-5** [comment]
How would we do that?

**Comment by JamesErvin-5** [comment]
If you feel up to the task, go for it!

**Comment by JamesErvin-5** [comment]
Just maybe make a fork so if you break the fork, you don't break the main.

**Comment by staticalliam7** [comment]
> How would we do that?

Not sure. It would be cool, but you would have to add parts and model them

**Comment by JamesErvin-5** [comment]
Maybe should we reach out to a few of the other modders? Maybe HebaruSan, Caerfinon, theJesuit, and/or ColdJ?

**Comment by staticalliam7** [comment]
> Maybe should we reach out to a few of the other modders? Maybe HebaruSan, Caerfinon, theJesuit, and/or ColdJ?

Good idea

**Comment by staticalliam7** [comment]
For anyone keeping an eye on this issue, I am currently looking into, should have some kind of information soon.

**Comment by JamesErvin-5** [comment]
This issue will continue to be followed in Staticalliam's TODO list.
